In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("data_jobs_salary_monthly.xlsx")

In [4]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills
0,Data Scientist,Data Scientist - TikTok Ads,"Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-02 15:01:03,False,True,United States,year,224500.0,NaN,TikTok,"['r', 'python', 'matlab', 'sql']"
1,Data Scientist,Data Scientist - Technical Platform,"Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-12 04:04:48,False,True,United States,year,157500.0,NaN,TikTok,"['sql', 'python']"
2,Data Scientist,Data Scientist - Computer Vision,"Paris, France",via Ai-Jobs.net,Full-time,False,France,2023-01-30 08:13:55,False,False,France,year,88128.0,NaN,digiRocks,"['python', 'c++', 'pytorch', 'tensorflow', 'ke..."
3,Data Scientist,Senior Actuarial Consultant and Data Scientist...,"Las Vegas, NV","via Las Vegas, NV - Geebo",Full-time,False,"California, United States",2023-01-27 00:05:41,False,True,United States,hour,NaN,24.0,UnitedHealth Group,"['r', 'python', 'vba', 'sas', 'sas', 'sql', 'd..."
4,Data Scientist,Data Scientist Digital Effectiveness Operation...,"Sun City, AZ",via ZipRecruiter,Full-time,False,"California, United States",2023-01-29 10:04:53,False,True,United States,year,105800.0,NaN,Cox Communications,"['sql', 'python', 'aws', 'pandas', 'numpy', 's..."

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3102 entries, 0 to 3101
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        3102 non-null   object
 1   job_title              3102 non-null   object
 2   job_location           3080 non-null   object
 3   job_via                3102 non-null   object
 4   job_schedule_type      3090 non-null   object
 5   job_work_from_home     3102 non-null   bool
 6   search_location        3102 non-null   object
 7   job_posted_date        3102 non-null   datetime64[ns]
 8   job_no_degree_mention  3102 non-null   bool
 9   job_health_insurance   3102 non-null   bool
 10  job_country            3102 non-null   object
 11  salary_rate            3102 non-null   object
 12  salary_year_avg        2287 non-null   float64
 13  salary_hour_avg        815 non-null    float64
 14  company_name           3102 non-null   object
 15  job_skills             2821 non-null   object
dtypes: bool(3), datetime64[ns](1), float64(2), object(10)
memory usage: 324.3+ KB

In [6]:
df.isnull().sum()

job_title_short             0
job_title                   0
job_location               22
job_via                     0
job_schedule_type          12
job_work_from_home          0
search_location             0
job_posted_date             0
job_no_degree_mention       0
job_health_insurance        0
job_country                 0
salary_rate                 0
salary_year_avg           815
salary_hour_avg          2287
company_name                0
job_skills                281
dtype: int64

In [8]:
df.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills'],
      dtype='object')

In [9]:
df.isnull().sum()

job_title_short             0
job_title                   0
job_location               22
job_via                     0
job_schedule_type          12
job_work_from_home          0
search_location             0
job_posted_date             0
job_no_degree_mention       0
job_health_insurance        0
job_country                 0
salary_rate                 0
salary_year_avg           815
salary_hour_avg          2287
company_name                0
job_skills                281
dtype: int64

In [12]:
df = df.dropna(subset=['salary_year_avg'])

In [13]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills
0,Data Scientist,Data Scientist - TikTok Ads,"Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-02 15:01:03,False,True,United States,year,224500.00000,NaN,TikTok,"['r', 'python', 'matlab', 'sql']"
1,Data Scientist,Data Scientist - Technical Platform,"Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-12 04:04:48,False,True,United States,year,157500.00000,NaN,TikTok,"['sql', 'python']"
2,Data Scientist,Data Scientist - Computer Vision,"Paris, France",via Ai-Jobs.net,Full-time,False,France,2023-01-30 08:13:55,False,False,France,year,88128.00000,NaN,digiRocks,"['python', 'c++', 'pytorch', 'tensorflow', 'ke..."
4,Data Scientist,Data Scientist Digital Effectiveness Operation...,"Sun City, AZ",via ZipRecruiter,Full-time,False,"California, United States",2023-01-29 10:04:53,False,True,United States,year,105800.00000,NaN,Cox Communications,"['sql', 'python', 'aws', 'pandas', 'numpy', 's..."
5,Data Scientist,Data Scientist - Marketing Analytics,"Irving, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-24 16:02:05,False,True,United States,year,115000.00000,NaN,Cottonwood Financial,"['sql', 'sas', 'sas', 'python', 'r']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3094,Data Analyst,"Data Analyst - Strategy, Transformation & Capa...","Coral Springs, FL",via Recruit.net,Full-time,False,"Florida, United States",2023-01-23 00:02:49,True,False,United States,year,76579.00000,NaN,North Lauderdale,['express']
3095,Data Analyst,BI Data Analyst IV,Anywhere,via Indeed,Full-time,True,"California, United States",2023-01-06 16:01:23,False,False,United States,year,115791.50000,NaN,Kern Health Systems,"['sql', 'sas', 'sas', 'excel']"
3098,Data Analyst,"Data Analyst, Talent Acquisition - REMOTE","Los Angeles, CA",via Indeed,Full-time,False,"California, United States",2023-01-20 13:01:27,False,False,United States,year,79928.40625,NaN,USC,"['python', 'sql', 'word', 'excel', 'outlook', ..."
3099,Data Engineer,Staff Data Engineer - Full Stack,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-01-18 01:12:46,False,False,India,year,147500.00000,NaN,Visa,"['java', 'nosql', 'db2', 'mysql', 'spring', 'r..."
3100,Data Analyst,Material Data Analyst II SKA,"Warner Robins, GA",via ZipRecruiter,Full-time,False,Georgia,2023-01-25 01:57:33,False,False,United States,year,56500.00000,NaN,"S & K Technologies, Inc.","['crystal', 'sql', 'c#', 'oracle', 'power bi',..."

In [14]:
df = df.dropna(subset=['job_country'])

In [15]:
df = df.dropna(subset=['company_name'])

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df = df.drop_duplicates()

In [19]:
df.dtypes

job_title_short                  object
job_title                        object
job_location                     object
job_via                          object
job_schedule_type                object
job_work_from_home                 bool
search_location                  object
job_posted_date          datetime64[ns]
job_no_degree_mention              bool
job_health_insurance               bool
job_country                      object
salary_rate                      object
salary_year_avg                 float64
salary_hour_avg                 float64
company_name                     object
job_skills                       object
dtype: object

In [20]:
df['Year'] = df['job_posted_date'].dt.year

In [21]:
df['salary_year_avg'].describe()

count      2287.000000
mean     123064.162150
std       47367.702396
min       32500.000000
25%       90000.000000
50%      115000.000000
75%      150000.000000
max      475000.000000
Name: salary_year_avg, dtype: float64

In [22]:
len(df)

2287

In [23]:
df['company_name'].nunique()

1262

In [24]:
df['job_country'].nunique()

65

In [25]:
df['salary_year_avg'].mean()

np.float64(123064.16214951355)

In [26]:
df['salary_year_avg'].max()

475000.0

In [28]:
df.to_excel("cleaned_jobs_salary.xlsx", index=False)

In [29]:
import pandas as pd

df = pd.read_excel("cleaned_jobs_salary.xlsx")
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,Year
0,Data Scientist,Data Scientist - TikTok Ads,"Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-02 15:01:03,False,True,United States,year,224500.0,NaN,TikTok,"['r', 'python', 'matlab', 'sql']",2023
1,Data Scientist,Data Scientist - Technical Platform,"Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-12 04:04:48,False,True,United States,year,157500.0,NaN,TikTok,"['sql', 'python']",2023
2,Data Scientist,Data Scientist - Computer Vision,"Paris, France",via Ai-Jobs.net,Full-time,False,France,2023-01-30 08:13:55,False,False,France,year,88128.0,NaN,digiRocks,"['python', 'c++', 'pytorch', 'tensorflow', 'ke...",2023
3,Data Scientist,Data Scientist Digital Effectiveness Operation...,"Sun City, AZ",via ZipRecruiter,Full-time,False,"California, United States",2023-01-29 10:04:53,False,True,United States,year,105800.0,NaN,Cox Communications,"['sql', 'python', 'aws', 'pandas', 'numpy', 's...",2023
4,Data Scientist,Data Scientist - Marketing Analytics,"Irving, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-24 16:02:05,False,True,United States,year,115000.0,NaN,Cottonwood Financial,"['sql', 'sas', 'sas', 'python', 'r']",2023

In [30]:
import os

print(os.getcwd())

C:\Users\Pranav

In [31]:
os.listdir()

['.anaconda',
 '.antigravity',
 '.bash_history',
 '.conda',
 '.continuum',
 '.copilot',
 '.dbus-keyrings',
 '.dia',
 '.gemini',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.junie',
 '.jupyter',
 '.lemminx',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.node_repl_history',
 '.th-client',
 '.virtual_documents',
 '.vscode',
 '.vscode-shared',
 'anaconda3',
 'ansel',
 'AppData',
 'Application Data',
 'cleaned_jobs_salary.xlsx',
 'Contacts',
 'Cookies',
 'data_jobs_salary_monthly.xlsx',
 'Documents',
 'Downloads',
 'Favorites',
 'hi.c',
 'hi.exe',
 'IdeaProjects',
 'Links',
 'Local Settings',
 'logs',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Oracle',
 'PrintHood',
 'Recent',
 'salary_analysis.ipynb',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Videos']

In [32]:
df.to_excel("cleaned_jobs_salary.xlsx", index=False)

In [33]:
print(os.getcwd())

C:\Users\Pranav